version: "3.6"

services:

    influxdb:
        image: influxdb:1.8
        restart: unless-stopped
        networks:
            - webgateway        
        env_file:
            - "influxdb.env"                  
        volumes:
            - ./data/influxdb:/var/lib/influxdb
            - ./influx_init.iql:/docker-entrypoint-initdb.d/influx_init.iql
networks:
    webgateway:
        external: true

